cache:
  key: "$CI_BUILD_REF_NAME/$CI_BUILD_STAGE"
  paths:
    - .composer/

variables:
  DOCKER_DRIVER: "overlay2"
  COMPOSER_CACHE_DIR: ".composer"
  COMPOSER_PROCESS_TIMEOUT: "1800"
  COMPOSER_ALLOW_SUPERUSER: "1"
  TYPO3_VERSION: ^7.6
  TYPO3_PATH_WEB: "$CI_PROJECT_DIR/.Build/Web"
  MYSQL_DATABASE: "typo3"
  MYSQL_ROOT_PASSWORD: "joh316"
  typo3DatabaseName: "typo3"
  typo3DatabaseHost: "mysql"
  typo3DatabaseUsername: "root"
  typo3DatabasePassword: "joh316"


.test: &test_php
  stage: test
  services:
    - mysql:5
  before_script:
    - apk --no-cache add bash curl git mercurial openssh openssl parallel subversion tini
    - docker-php-ext-install mysqli
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --no-ansi --install-dir=/usr/bin --filename=composer
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - rm composer.lock
    - composer require typo3/cms="${TYPO3_VERSION}"
  script:
    - find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}'
  tags:
    - docker

typo3_7lts 1/4:
  <<: *test_php
  image: php:5.5-alpine

typo3_7lts 2/4:
  <<: *test_php
  image: php:5.6-alpine

typo3_7lts 3/4:
  <<: *test_php
  image: php:7.0-alpine

typo3_7lts 4/4:
  <<: *test_php
  image: php:7.1-alpine

typo3_8lts 1/2:
  <<: *test_php
  image: php:7.0-alpine
  variables:
    TYPO3_VERSION: ^8

typo3_8lts 2/2:
  <<: *test_php
  image: php:7.1-alpine
  variables:
    TYPO3_VERSION: ^8
